TOGBankClassic_Core = LibStub("AceAddon-3.0"):NewAddon("TOGBankClassic", "AceComm-3.0", "AceConsole-3.0", "AceEvent-3.0", "AceSerializer-3.0", "AceTimer-3.0")
local AceComm_SendCommMessage = TOGBankClassic_Core.SendCommMessage

-- NS-001: aliased as a file-scope local so a foreign global of the same name cannot be read
-- instead. See the header of Modules/Constants.lua.
local COMM_PREFIX_DESCRIPTIONS = TOGBankClassic_Constants.COMM_PREFIX_DESCRIPTIONS

--- The SEND log's name for a prefix. TOGBank's own come from Constants; the DeltaSync host's seven
--- (`togban-q`, `togban-r`, ...) are generated by the library from the namespace, so they are read
--- off the host rather than listed twice -- commprefix_spec pins Constants to the prefixes Chat
--- registers, and the host registers its own.
local hostPrefixNames
local function DescribePrefix(prefix)
    local own = COMM_PREFIX_DESCRIPTIONS[prefix]
    if own then return own end
    if not hostPrefixNames then
        hostPrefixNames = {}
        local host = TOGBankClassic_Core.DeltaHost and TOGBankClassic_Core:DeltaHost()
        for channel, p in pairs(host and host.prefixes or {}) do
            hostPrefixNames[p] = "(DeltaSync " .. channel .. ")"
        end
    end
    return hostPrefixNames[prefix] or "(Unknown)"
end

-- RAID-SYNC-001: the one raid guard, shared with the receive gate and the status bar.
local SyncPausedByRaid = TOGBankClassic_Constants.SyncPausedByRaid

function TOGBankClassic_Core:SendCommMessage(prefix, text, distribution, target, prio, callbackFn, callbackArg)
    local prefixDesc = DescribePrefix(prefix)
    if SyncPausedByRaid() then
        TOGBankClassic_Output:Debug("COMMS", "SUPPRESS", "< (suppressing) %s %s (in raid)", prefix, prefixDesc)
        -- RAID-VISIBILITY-001: say so ONCE per raid membership, in plain chat. The guard is right
        -- (the chat channel is throttled and raid addons need it) but it was invisible -- the
        -- collect and dispatch timers kept printing "no offers" as if the guild were quiet, and the
        -- operator spent an afternoon on 2026-09-12 believing sync was broken: "i was in a raid, do
        -- you stop syncs while in a raid?" -- "i wasn't aware". Reset by the first send after leaving.
        if not self.raidSuppressNoticed then
            self.raidSuppressNoticed = true
            TOGBankClassic_Output:Info("Guild bank sync is paused while you are in a raid group; it resumes when you leave. (Settings > General > Keep syncing in a raid group)")
        end
        -- Unblock the AceCommQueue waiting on this send (0 >= 0 triggers last-chunk detection).
        if callbackFn then callbackFn(callbackArg, 0, 0, nil) end
        return
    end
    self.raidSuppressNoticed = nil
    if not AceComm_SendCommMessage then
        if callbackFn then callbackFn(callbackArg, 0, 0, nil) end
        return
    end

    local bytes = text and #text or 0
    local dest = (target and target ~= "") and (distribution .. "/" .. target) or distribution
    TOGBankClassic_Output:Debug("COMMS", "SEND", "< %s %s to %s (%d bytes)", prefix, prefixDesc, dest, bytes)

    return AceComm_SendCommMessage(self, prefix, text, distribution, target, prio, callbackFn, callbackArg)
end
-- AceCommQueue-1.0 must be embedded AFTER the SendCommMessage wrapper above so the queue
-- wraps the complete chain (raid guard + debug logging) rather than raw AceComm.
local ACQ = LibStub("AceCommQueue-1.0")
ACQ:Embed(TOGBankClassic_Core)
ACQ:RegisterSlashCommand("/acq")

--- The name a directed addon message is ADDRESSED to, from TOGBank's `Name-Realm` spelling: the
--- realm suffix is stripped for a same-realm target, kept for a cross-realm one. THE ONE address
--- rule (peer review F4): SendWhisper and every directed send on the DeltaSync host
--- (Modules/Inventory/Sync.lua) go through it, so the handshake and the data reply are addressed
--- identically by construction -- a reply addressed differently from the request that earned it
--- would be lost while every handshake worked. DeltaSync's guild-mode stamp re-qualifies the
--- target through the roster before writing it (DeltaSyncGuildMode.lua GM:Stamp), so handing the
--- host a stripped same-realm name produces the same stamp a full one would (peer review A4).
---@param target string
---@return string address
function TOGBankClassic_Core:WhisperAddress(target)
    if target and string.find(target, "-") then
        local left, right = string.match(target, "^(.-)%-(.+)$")
        local currentRealm = GetNormalizedRealmName()
        if left and right and currentRealm and right == currentRealm then
            return left
        end
    end
    return target
end

-- Centralized WHISPER send with automatic online check
-- Returns true if sent, false if target offline or send failed
function TOGBankClassic_Core:SendWhisper(prefix, text, target, prio, callbackFn, callbackArg)
    -- Check if target is online
    local isOnline = TOGBankClassic_Guild:IsPlayerOnline(target)
    TOGBankClassic_Output:Debug("PROTOCOL", "WHISPER", "[WHISPER-DEBUG] SendWhisper called: prefix=%s, target=%s, isOnline=%s",
        prefix, target, tostring(isOnline))

    if not isOnline then
        TOGBankClassic_Output:Debug("WHISPER", "SKIP", "[WHISPER-DEBUG] Cannot send %s WHISPER to %s - player is offline", prefix, target)
        return false
    end

    local nameOnly = self:WhisperAddress(target)

    TOGBankClassic_Output:Debug("PROTOCOL", "WHISPER", "[WHISPER-DEBUG] Attempting SendCommMessage: prefix=%s, target=%s, nameOnly=%s", prefix, target, nameOnly)

    -- Send the whisper (AceComm returns nil on success, which is truthy behavior we want)
    self:SendCommMessage(prefix, text, "WHISPER", nameOnly, prio, callbackFn, callbackArg)

    TOGBankClassic_Output:Debug("PROTOCOL", "WHISPER", "[WHISPER-DEBUG] SendCommMessage completed for %s to %s", prefix, nameOnly)

    -- If we got this far, player is online and whisper was sent
    return true
end

function TOGBankClassic_Core:OnInitialize()
    TOGBankClassic_Output:Init()
    TOGBankClassic_Performance:Initialize()
    TOGBankClassic_Database:Init()
    -- DS-HOST-001: stand the DeltaSync host up here, after Output and the database exist, so its
    -- seven prefixes register at login rather than at the first send. Lazy-created otherwise.
    self:DeltaHost()
    TOGBankClassic_Chat:Init()
    TOGBankClassic_Options:Init()
    TOGBankClassic_Chat:RegisterAliasCommands()
    -- ROSTER-003: bind LibGuildRoster's presence callbacks before events register, so no
    -- online/offline transition is missed during login. Idempotent and safe if the library
    -- is absent (falls back to the legacy roster scan).
    TOGBankClassic_Guild:InitRosterCallbacks()
    -- INV2: attach the V2 SavedVariable. Cheap and side-effect free -- it only ensures the
    -- table exists. Done unconditionally rather than behind the switch so that turning
    -- inventoryV2 on mid-session does not need a reload to start collecting.
    if TOGBankClassic_Inventory_Store then
        TOGBankClassic_Inventory_Store:Init()
        -- DOUBLE-001: said out loud, once, so a banker whose counts were doubled knows why they
        -- just changed and that the next scan republishes the corrected record.
        local repaired = TOGBankClassic_Inventory_Store.repaired or 0
        if repaired > 0 then
            TOGBankClassic_Output:Info("Repaired %d bank record(s) that were counting items twice (a received copy stored beside your own scan). The next scan publishes the corrected counts.", repaired)
        end
    end
    TOGBankClassic_UI:Init()

    if TOGBankClassic_ItemHighlight and TOGBankClassic_ItemHighlight.Initialize then
        TOGBankClassic_ItemHighlight:Initialize()
    end

    if TOGBankClassic_TooltipBankerInfo and TOGBankClassic_TooltipBankerInfo.Initialize then
        TOGBankClassic_TooltipBankerInfo:Initialize()
    end

    self:ScheduleRepeatingTimer(function()
        TOGBankClassic_Performance:RecordMemory("periodic")
    end, 300)

    -- Enable VersionCheck-1.0 addon integration
    do
        local VC = LibStub:GetLibrary("VersionCheck-1.0", true)
        if VC and VC.Enable then
            -- Create a host addon object for VersionCheck
            local hostAddon = {
                GetName = function() return "TOGBankClassic" end,
                Version = GetAddOnMetadata("TOGBankClassic", "Version") or "@project-version@"
            }
            VC:Enable(hostAddon)
            TOGBankClassic_Output:Debug("PROTOCOL", "INIT", "VersionCheck-1.0 integration enabled (v%s)", hostAddon.Version)
        end
    end
end

function TOGBankClassic_Core:OnEnable()
    TOGBankClassic_Events:RegisterEvents()
end

function TOGBankClassic_Core:OnDisable()
    TOGBankClassic_Events:UnregisterEvents()
end

-- ============================================================================
-- DS-HOST-001: THE DeltaSync-1.0 HOST
-- ============================================================================
-- Step 2 of THE DELTA RELEASE (docs/DELTA_RELEASE.md section 5). The operator, 2026-09-11: "rip it
-- out and use the library" -- TOGBank's own sync frameworks give way to DeltaSync. Until this,
-- DeltaSync was a declared dependency that nothing called: Core carried its own byte-identical
-- copies of the library's checksum and `<AceSerialized>\030<checksum>\031END` envelope (~140 lines,
-- the "duplicate envelope code" LIBREQ-DS-003 named). Those copies are deleted; the three public
-- methods below delegate to the host. deltahost_spec pins the envelope for a fixed payload as a
-- literal captured from Core's OWN implementation before the delegation, so "byte-identical" is
-- proven rather than reasoned -- every peer on every prior version parses this exact framing.
--
-- What the host carries: the envelope and the checksum (DS-HOST-001), and since step 3b the DATA
-- LEG of every sync -- a requester's QUERY naming the canon it holds (`host:RequestData`), and the
-- provider's RESPONSE carrying the delta chain, the snapshot or a no-change (`host:SendData`;
-- Modules/Inventory/Sync.lua). Its seven comm prefixes are registered at creation. The numbered
-- handshake (P2P-035) is still TOGBank's own layer on `togbank-rr` until LIBREQ-DS-008 moves it into
-- the library; the host's InitP2P is deliberately NOT called, because per-item hash offers are the
-- design banker numbers replaced.
--
-- DEBUG: the host gets a LOGGER (LIBREQ-DS-003's shape), so DeltaSync claims no chat tab and does
-- no filtering of its own. Every library line lands in Output:Debug under the DELTASYNC category,
-- with the library's own category as the tag -- and its tag, when it has one, joined on
-- (`COMMS-SEND`) -- so one TOGBank toggle gates the library and its lines still filter.
local deltaHost

--- Route a DeltaSync debug call into Output. The library calls its logger with the RAW arguments
--- of lib:Debug -- (category, tag, fmt, ...) / (category, fmt, ...) / (fmt, ...) -- and leaves the
--- resolution to the host. The rule mirrors Output:Debug's own DEBUG-001 shape test: a bare
--- SCREAMING token followed by at least one more argument is a category or a tag.
local DS_CATEGORIES = {
    INIT = true, HASH = true, COMMS = true, DELTA = true,
    VALIDATE = true, SERIALIZE = true, P2P = true, ROSTER = true,
}
local function DeltaSyncLogger(fmt, ...)
    if type(fmt) == "string" and DS_CATEGORIES[fmt] and select("#", ...) > 0 then
        local category, second = fmt, (select(1, ...))
        if type(second) == "string" and select("#", ...) > 1 and second:match("^[%u%d%-_]+$") then
            return TOGBankClassic_Output:Debug("DELTASYNC", category .. "-" .. second, select(2, ...))
        end
        return TOGBankClassic_Output:Debug("DELTASYNC", category, ...)
    end
    return TOGBankClassic_Output:Debug("DELTASYNC", fmt, ...)
end

-- ---------------------------------------------------------------------------------------------
-- DS-HOST-002: THE TRANSPORT PROXY, and the one thing it adds -- a per-send completion.
-- ---------------------------------------------------------------------------------------------
-- DeltaSync sends through `aceAddon:SendCommMessage` and receives through `aceAddon:RegisterComm`;
-- that is the whole of what it asks of the object. It exposes no "this send has LEFT" hook -- its
-- `onSendFailed` fires only for a refusal, and `sendsDelivered` is a counter with no identity. The
-- P2P send slot (P2P-024/028) must be released when the reply has drained, not when it was queued,
-- or three queued snapshots count as no load and the cap admits a fourth. LIBREQ-DS-009 asks the
-- library for the callback; until it ships, this proxy is the reference implementation: it forwards
-- both methods to Core unchanged and, on the way through, chains the delivery callback so a watcher
-- registered for (prefix, target) hears the whole-message verdict exactly once.
--
-- A watcher is CONSUMED by the first send matching its key. `host:SendData` sends synchronously
-- inside the call, so "register, then SendData" cannot be interleaved by another send to the same
-- target; a send the library refuses before reaching the proxy (its roster online-guard) never
-- consumes the watcher, which is why callers Unwatch on a false return.
local hostSendWatchers = {}

--- Hear the verdict of the NEXT host send on `prefix` to `target`: fn(delivered, reason).
function TOGBankClassic_Core:WatchHostSend(prefix, target, fn)
    hostSendWatchers[tostring(prefix) .. "|" .. tostring(target)] = fn
end

function TOGBankClassic_Core:UnwatchHostSend(prefix, target)
    hostSendWatchers[tostring(prefix) .. "|" .. tostring(target)] = nil
end

local function HostTransport()
    local Core = TOGBankClassic_Core
    return {
        name = "TOGBankClassic",
        -- Read by the library's status report only: whether the callback is one terminal verdict.
        __AceCommQueue_embedded = Core.__AceCommQueue_embedded,
        RegisterComm = function(_, prefix, handler)
            return Core:RegisterComm(prefix, handler)
        end,
        SendCommMessage = function(_, prefix, text, distribution, target, prio, callbackFn, callbackArg)
            local key = tostring(prefix) .. "|" .. tostring(target)
            local watcher = hostSendWatchers[key]
            hostSendWatchers[key] = nil
            local function onResult(arg, sent, total, delivered, reason)
                if callbackFn then callbackFn(arg, sent, total, delivered, reason) end
                -- TERMINAL means the message's fate is known: it all went (sent >= total), or it
                -- did not go at all -- refused (`false`), or never attempted (`nil`: the raid
                -- guard above reports (0, 0, nil)). Under AceCommQueue there is exactly one
                -- callback and it is terminal whatever it says; the `delivered ~= true` half is
                -- what keeps a refusal terminal if a per-chunk transport ever reports one early.
                if watcher and (delivered ~= true or (total or 0) == 0 or (sent or 0) >= total) then
                    local fn = watcher
                    watcher = nil
                    fn(delivered == true, reason)
                end
            end
            return Core:SendCommMessage(prefix, text, distribution, target, prio, onResult, callbackArg)
        end,
    }
end

--- The host, created on first use. Lazy rather than only in OnInitialize because the envelope is
--- reachable before OnInitialize runs (a spec that loads Core and serializes; a comm handler bound
--- early), and a host that does not exist yet must not turn into a nil index at the first send.
---@return table host the DeltaSync-1.0 host object
function TOGBankClassic_Core:DeltaHost()
    if deltaHost then return deltaHost end
    local DS = LibStub("DeltaSync-1.0")
    deltaHost = DS:NewHost({
        namespace = "TOGBankClassic",
        aceAddon  = HostTransport(),
        logger    = DeltaSyncLogger,
        -- THE DATA LEG (THE DELTA RELEASE step 3b): a QUERY names the canon a requester holds and
        -- the alt it wants; a RESPONSE is the chain, the snapshot, or a no-change. Inventory/Sync
        -- owns both directions; the closures look it up at call time because Core loads last.
        onDataRequest = function(sender, baseline)
            local Sync = TOGBankClassic_Inventory_Sync
            if Sync then Sync:OnDataRequest(sender, baseline) end
        end,
        onDataReceived = function(sender, data, len)
            local Sync = TOGBankClassic_Inventory_Sync
            if Sync then Sync:OnDataReceived(sender, data, len) end
        end,
        -- A send the client REFUSED -- the message never left. Worth a warning-level line: it is
        -- the failure that otherwise looks like a quiet peer.
        onSendFailed = function(info)
            TOGBankClassic_Output:Debug("DELTASYNC", "COMMS-SKIP",
                "send refused by the client: prefix=%s dist=%s target=%s bytes=%s",
                tostring(info and info.prefix), tostring(info and info.distribution),
                tostring(info and info.target), tostring(info and info.bytes))
        end,
    })
    return deltaHost
end

--- The multiplicative checksum DeltaComms feeds the hash input string through (HASH-PIN-001). A
--- STRING through the library's revision-1 ComputeHash is exactly that checksum over exactly those
--- bytes (SerializeForHash renders a string as itself); a non-string answers 0, as before.
function TOGBankClassic_Core:Checksum(str)
    if type(str) ~= "string" then return 0 end
    return self:DeltaHost():ComputeHash(str)
end

-- Serialize data with appended checksum and stop-marker for integrity verification.
-- Wire format:  <AceSerialized> \030 <checksum> \031END  -- the host's, byte for byte.
function TOGBankClassic_Core:SerializeWithChecksum(data)
    return self:DeltaHost():SerializeWithChecksum(data)
end

-- Deserialize data and verify integrity; returns success, data (or false, error) -- AceSerializer's
-- two-return contract, which the host keeps. The host runs the stop-marker and CRC checks and logs
-- an INTEGRITY-MISMATCH line (through the logger above) when they disagree; what stays here is the
-- tester opt-in chat alert, which the library rightly does not own.
--
-- Optional ctx table for richer diagnostics: { sender, prefix, distribution }
---@param message string
---@param ctx? table
function TOGBankClassic_Core:DeserializeWithChecksum(message, ctx)
    local ok, result = self:DeltaHost():DeserializeWithChecksum(message, ctx)
    if not ok and type(result) == "string" and result:find("CRC mismatch", 1, true)
        and TOGBankClassic_Options and TOGBankClassic_Options:IsIntegrityCheckDiagnosticsEnabled() then
        DEFAULT_CHAT_FRAME:AddMessage("|cFFFF0000[TOGBankClassic ERROR]|r Integrity mismatch: " ..
            "message complete but CRC failed. from=" .. tostring(ctx and ctx.sender or "?") ..
            " prefix=" .. tostring(ctx and ctx.prefix or "?") ..
            " dist=" .. tostring(ctx and ctx.distribution or "?") ..
            " bytes=" .. tostring(type(message) == "string" and #message or 0) ..
            " (" .. result .. ") — please report to developers!")
    end
    return ok, result
end

-- INV2 step 10: `Core:ValidateDeltaStructure` was deleted here. It delegated to the DeltaComms
-- validator for the `alt-delta` envelope, and both went with the legacy link wire format. Its only
-- caller was the `alt-delta` receive branch in Chat.lua, which is also gone. A tuple payload is
-- validated by shape in `Wire.isV2` / `Wire.decode` instead.

function TOGBankClassic_Core:ComputeInventoryHash(bank, bags, mail, money)
	return TOGBankClassic_DeltaComms:ComputeInventoryHash(bank, bags, mail, money)
end

--- HASH-REV-001: the frozen revision-1 hash. See DeltaComms' `hashInventoryItemsV1` before touching.
function TOGBankClassic_Core:ComputeLegacyInventoryHash(bank, bags, mail, money)
	return TOGBankClassic_DeltaComms:ComputeLegacyInventoryHash(bank, bags, mail, money)
end

--- HASH-REV-001: stamp both revisions onto an alt from one item set. Every site that writes
--- `alt.inventoryHash` goes through this, so the two revisions cannot come from different scans.
--- HASH-CANON-003: `updatedAt` is forwarded so `inventoryHashV2` is the DTS-bearing CANON. Omitting
--- it does not error -- it produces a canon stamped `@0`, which is a real value that simply never
--- matches an author's -- so the parameter is not optional in practice even though Lua allows it.
function TOGBankClassic_Core:StampInventoryHashes(alt, bank, bags, mail, money, updatedAt)
	return TOGBankClassic_DeltaComms:StampInventoryHashes(alt, bank, bags, mail, money, updatedAt)
end
